import { useState, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useWorkspace } from './useWorkspace';
import { toast } from 'sonner';

export interface CopyVariation {
  index: number;
  subject_line: string;
  body: string;
  patterns_used: string[];
  quality_score: number;
  word_count: number;
  variation_style: string;
  validation: {
    is_valid: boolean;
    issues: string[];
    warnings: string[];
  };
}

export interface GenerationContext {
  best_practices_count: number;
  winning_patterns_count: number;
  top_copy_count: number;
  industry_intel_count: number;
}

export interface GenerationResult {
  variations: CopyVariation[];
  context_used: GenerationContext;
}

export interface GenerationRequest {
  channel: string;
  sequenceStep: string;
  buyerName?: string;
  buyerWebsite?: string;
  targetIndustry?: string;
  painPoints?: string;
  emailGoal?: string;
  callTranscript?: string;
  documentPaths?: string[];
  tone: string;
  variationCount?: number;
}

export interface BestPractice {
  id: string;
  channel: string;
  category: string;
  practice_type: string;
  name: string;
  description: string | null;
  config: Record<string, unknown>;
  performance_lift: number | null;
  source: string | null;
}

export function useCopywritingStudio() {
  const { currentWorkspace } = useWorkspace();
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [bestPractices, setBestPractices] = useState<BestPractice[]>([]);
  const [isLoadingPractices, setIsLoadingPractices] = useState(false);

  const fetchBestPractices = useCallback(async (channel?: string) => {
    setIsLoadingPractices(true);
    try {
      let query = supabase
        .from('channel_best_practices')
        .select('*')
        .eq('is_active', true);

      if (channel) {
        query = query.eq('channel', channel);
      }

      const { data, error } = await query;

      if (error) throw error;
      setBestPractices((data || []).map(item => ({
        ...item,
        config: (item.config as Record<string, unknown>) || {},
        description: item.description ?? null,
        performance_lift: item.performance_lift ?? null,
        source: item.source ?? null,
      })));
    } catch (error) {
      console.error('Error fetching best practices:', error);
      toast.error('Failed to load best practices');
    } finally {
      setIsLoadingPractices(false);
    }
  }, []);

  const generateCopy = useCallback(async (request: GenerationRequest) => {
    if (!currentWorkspace?.id) {
      toast.error('No workspace selected');
      return null;
    }

    setIsGenerating(true);
    setResult(null);

    try {
      const { data, error } = await supabase.functions.invoke('generate-copy', {
        body: {
          ...request,
          workspaceId: currentWorkspace.id,
        },
      });

      if (error) {
        // Handle specific error types
        if (error.message?.includes('429')) {
          toast.error('Rate limit exceeded. Please try again in a moment.');
        } else if (error.message?.includes('402')) {
          toast.error('Credits depleted. Please add credits to continue.');
        } else {
          throw error;
        }
        return null;
      }

      if (data?.error) {
        throw new Error(data.error);
      }

      setResult(data);
      toast.success(`Generated ${data.variations?.length || 0} variations`);
      return data;
    } catch (error) {
      console.error('Error generating copy:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to generate copy');
      return null;
    } finally {
      setIsGenerating(false);
    }
  }, [currentWorkspace?.id]);

  const saveToLibrary = useCallback(async (variation: CopyVariation, category: string) => {
    if (!currentWorkspace?.id) {
      toast.error('No workspace selected');
      return false;
    }

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { error } = await supabase
        .from('copy_library')
        .insert({
          workspace_id: currentWorkspace.id,
          created_by: user.id,
          subject_line: variation.subject_line,
          email_body: variation.body,
          body_preview: variation.body.substring(0, 200),
          category,
          status: 'draft',
          is_template: true,
          ai_tags: variation.patterns_used,
          notes: `Generated by Copywriting Studio. Style: ${variation.variation_style}. Score: ${variation.quality_score}/100`,
        });

      if (error) throw error;
      toast.success('Saved to Copy Library');
      return true;
    } catch (error) {
      console.error('Error saving to library:', error);
      toast.error('Failed to save to library');
      return false;
    }
  }, [currentWorkspace?.id]);

  return {
    isGenerating,
    result,
    bestPractices,
    isLoadingPractices,
    generateCopy,
    fetchBestPractices,
    saveToLibrary,
    clearResult: () => setResult(null),
  };
}
