-- Add a flag to mark synthetic / estimated rows generated by backfills
ALTER TABLE public.daily_metrics
ADD COLUMN IF NOT EXISTS is_estimated boolean NOT NULL DEFAULT false;

-- Helpful index for engagement report queries
CREATE INDEX IF NOT EXISTS idx_daily_metrics_engagement_date
ON public.daily_metrics (engagement_id, date);

-- Helpful partial index to find engagements relying on estimated data
CREATE INDEX IF NOT EXISTS idx_daily_metrics_estimated
ON public.daily_metrics (engagement_id)
WHERE is_estimated = true;